import { useEffect, useMemo, useRef, useState } from 'react';

type Msg={type:string;[k:string]:any};
const P:Record<string,string>={twitch:'Twitch',youtube:'YouTube',kick:'Kick',tiktok:'TikTok'};
function useQuery(){return useMemo(()=>new URLSearchParams(location.search),[])}
function wsUrl(user:string,token:string,widget:string){const proto=location.protocol==='https:'?'wss:':'ws:';return `${proto}//${location.host}/room/${encodeURIComponent(user)}/ws?token=${encodeURIComponent(token)}&role=overlay&widget=${encodeURIComponent(widget)}`}
function audio(url?:string,volume=80){if(!url)return;const a=new Audio(url);a.volume=Math.max(0,Math.min(1,Number(volume)/100));void a.play().catch(()=>{});}

export function Overlay(){
 const q=useQuery(),user=q.get('user')||'',token=q.get('token')||'',widget=q.get('widget')||'layout',resource=q.get('resource')||'';
 const [config,setConfig]=useState<any[]>([]),[chat,setChat]=useState<any[]>([]),[alert,setAlert]=useState<any|null>(null),[stickers,setStickers]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[counters,setCounters]=useState<Record<string,any>>({}),[connected,setConnected]=useState(false);const timers=useRef<Map<string,number>>(new Map());
 useEffect(()=>{if(!user||!token)return;fetch(`/api/overlay/config/${user}?token=${encodeURIComponent(token)}`).then(r=>r.ok?r.json():Promise.reject()).then(j=>setConfig(j.items||[])).catch(()=>{})},[user,token]);
 useEffect(()=>{if(!user||!token)return;let stop=false,ws:WebSocket|undefined,retry=500;const open=()=>{if(stop)return;ws=new WebSocket(wsUrl(user,token,widget));ws.onopen=()=>{setConnected(true);retry=500};ws.onclose=()=>{setConnected(false);if(!stop){setTimeout(open,retry);retry=Math.min(8000,retry*1.6)}};ws.onmessage=e=>{let m:Msg;try{m=JSON.parse(String(e.data))}catch{return} onMessage(m)}};const onMessage=(m:Msg)=>{if(m.type==='counterUpdate'){setCounters(v=>({...v,[m.id]:m}))} if(m.type==='botReply'){setChat(v=>[...v.slice(-60),{type:'chat_message',platform:m.platform,actorName:m.actorName||'MonaBot',message:m.message,createdAt:new Date().toISOString()}])} if(m.type==='event'){const ev=m.event;if(ev?.type==='chat_message'||ev?.message||['sub','gift','super_chat','super_sticker','bits','membership','gift_sub'].some(x=>String(ev?.type).includes(x))){setChat(v=>[...v.slice(-60),ev])}} if(m.type==='alert'){if(resource&&m.profile?.id!==resource)return;setAlert(m);audio(m.profile?.soundUrl,m.profile?.volume);const id=String(m.id);const old=timers.current.get(id);if(old)clearTimeout(old);timers.current.set(id,window.setTimeout(()=>setAlert(a=>a?.id===m.id?null:a),Math.max(1500,Number(m.profile?.duration||6)*1000)))} if(m.type==='redemption'){if(resource&&m.resource?.id!==resource)return;if(m.kind==='sticker'){const item={...m,key:m.id};setStickers(v=>[...v,item]);setTimeout(()=>setStickers(v=>v.filter(x=>x.key!==item.key)),Math.max(1200,Number(m.resource?.duration||5)*1000))}if(m.kind==='sound')audio(m.resource?.assetUrl,m.resource?.volume);if(m.kind==='media-request'&&m.request){setMedia(v=>[...v,{...m,key:m.id}])}}};open();return()=>{stop=true;ws?.close();timers.current.forEach(x=>clearTimeout(x));timers.current.clear()}},[user,token,widget,resource]);
 if(!user||!token)return <div className="overlay-error">Faltan user/token en la URL de MonaWorld.</div>;
 const full=config.find(x=>x.kind==='overlay'&&x.data?.full===true);const visibleConfig=resource?config.filter(x=>x.id===resource):config;
 if(widget==='chat')return <ChatView rows={chat} connected={connected}/>;
 if(widget==='alerts')return <AlertView alert={alert}/>;
 if(widget==='stickers')return <StickerLayer items={stickers}/>;
 if(widget==='sounds')return <div/>;
 if(widget==='media')return <MediaView item={media[0]} onDone={()=>setMedia(v=>v.slice(1))}/>;
 if(widget==='overlay')return <GenericOverlay resources={visibleConfig} chat={chat} alert={alert} stickers={stickers}/>;
 return <FullLayout widgets={full?.data?.widgets||[]} chat={chat} alert={alert} stickers={stickers} media={media[0]} counters={counters} onMediaDone={()=>setMedia(v=>v.slice(1))} connected={connected}/>;
}
function ChatView({rows,connected}:{rows:any[];connected:boolean}){return <div className="chat-root"><div className="connection-pill" data-ok={connected}>{connected?'LIVE':'RECONECTANDO'}</div><div className="chat-list">{rows.map((r,i)=><div className={`chat-message ${r.platform||''}`} key={`${r.id||r.createdAt||i}:${i}`}><div className="chat-head"><b>{r.actorName||r.username||'Usuario'}</b><span>{P[r.platform]||r.platform}</span></div>{r.message&&<div className="chat-text">{r.message}</div>}{r.type!=='chat_message'&&<div className="chat-event">{String(r.type||'evento').replaceAll('_',' ')} {r.amount?`· ${r.amount} ${r.currency||r.rawUnit||''}`:''} {r.giftName?`· ${r.giftName}`:''}</div>}</div>)}</div></div>}
function AlertView({alert}:{alert:any}){if(!alert)return null;const p=alert.profile||{},ev=alert.event||{};const text=String(p.text||'{user} apoyó el canal!').replaceAll('{user}',ev.actorName||'Usuario').replaceAll('{amount}',String(ev.amount||''));return <div className="alert-root" style={{transform:`scale(${Math.max(.3,Number(p.size||100)/100)})`}}>{p.mediaUrl&&(/\.(mp4|webm)(\?|$)/i.test(p.mediaUrl)?<video src={p.mediaUrl} autoPlay muted loop={false}/>:<img src={p.mediaUrl}/>)}<div className="alert-text">{text}</div>{ev.giftName&&<div className="alert-sub">{ev.giftName}</div>}</div>}
function StickerLayer({items}:{items:any[]}){return <div className="sticker-layer">{items.map((x,i)=>{const pos=x.resource?.position||'random';const left=pos==='fixed'?50:10+((i*23+17)%75),top=pos==='top'?8:pos==='center'?45:pos==='bottom'?76:12+((i*31+11)%70);return <img key={x.key} src={x.resource?.assetUrl} className="sticker" style={{left:`${left}%`,top:`${top}%`}}/>})}</div>}

function youtubeId(raw:string){try{const u=new URL(raw);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||'';return ''}catch{return ''}}
function MediaView({item,onDone}:{item:any;onDone:()=>void}){const id=item?youtubeId(String(item.request||'')):'';useEffect(()=>{if(!item)return;const ms=Math.max(30,Number(item.resource?.maxMinutes||8)*60)*1000;const t=setTimeout(onDone,ms);return()=>clearTimeout(t)},[item,onDone]);if(!item||!id)return null;return <div className="media-player"><iframe src={`https://www.youtube.com/embed/${encodeURIComponent(id)}?autoplay=1&controls=0&rel=0`} allow="autoplay; encrypted-media" allowFullScreen/><div className="media-credit">Pedido por {item.viewer?.name||'viewer'}</div></div>}

function FullLayout({widgets,chat,alert,stickers,media,counters,onMediaDone,connected}:{widgets:any[];chat:any[];alert:any;stickers:any[];media:any;counters:Record<string,any>;onMediaDone:()=>void;connected:boolean}){return <div className="layout-root"><StickerLayer items={stickers}/>{widgets.filter(w=>w.visible!==false).map(w=><div key={w.id} className="layout-widget" style={{left:`${w.x}%`,top:`${w.y}%`,width:`${w.w}%`,height:`${w.h}%`}}>{w.type==='chat'?<ChatView rows={chat.slice(-12)} connected={connected}/>:w.type==='alerts'?<AlertView alert={alert}/>:w.type==='stickers'?<StickerLayer items={stickers}/>:w.type==='media'?<MediaView item={media} onDone={onMediaDone}/>:w.type==='counter'?<div className="counter-widget"><b>{w.label||'Contador'}</b><strong>{Object.values(counters)[0]?.value??'0'}</strong></div>:w.type==='sounds'?null:<div className="widget-placeholder">{w.label||w.type}</div>}</div>)}</div>}
function GenericOverlay({resources,chat,alert,stickers}:{resources:any[];chat:any[];alert:any;stickers:any[]}){const r=resources[0];if(!r)return null;if(r.data?.widget==='chat')return <ChatView rows={chat} connected/>;if(r.data?.widget==='image'&&r.data?.assetUrl)return <img className="generic-image" src={r.data.assetUrl}/>;if(r.data?.widget==='text')return <div className="generic-text">{r.data?.text||r.name}</div>;return <div className="generic-text">{r.data?.text||r.name}</div>}
