import type { WorkerEnv } from './env.js';
import { randomToken } from './auth.js';
export type OAuthPlatform='twitch'|'youtube'|'kick'|'tiktok';
interface Provider { auth:string; token:string; clientId:(e:WorkerEnv)=>string|undefined; clientSecret:(e:WorkerEnv)=>string|undefined; scopes:string[]; pkce:boolean; }
const PROVIDERS:Record<OAuthPlatform,Provider>={
 twitch:{auth:'https://id.twitch.tv/oauth2/authorize',token:'https://id.twitch.tv/oauth2/token',clientId:e=>e.TWITCH_CLIENT_ID,clientSecret:e=>e.TWITCH_CLIENT_SECRET,scopes:['user:read:email','moderator:read:followers','channel:read:subscriptions','bits:read','user:read:chat','user:bot','channel:bot'],pkce:false},
 youtube:{auth:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',clientId:e=>e.YOUTUBE_CLIENT_ID,clientSecret:e=>e.YOUTUBE_CLIENT_SECRET,scopes:['openid','profile','email','https://www.googleapis.com/auth/youtube.readonly'],pkce:true},
 kick:{auth:'https://id.kick.com/oauth/authorize',token:'https://id.kick.com/oauth/token',clientId:e=>e.KICK_CLIENT_ID,clientSecret:e=>e.KICK_CLIENT_SECRET,scopes:['user:read','channel:read','events:subscribe'],pkce:true},
 tiktok:{auth:'https://www.tiktok.com/v2/auth/authorize/',token:'https://open.tiktokapis.com/v2/oauth/token/',clientId:e=>e.TIKTOK_CLIENT_KEY,clientSecret:e=>e.TIKTOK_CLIENT_SECRET,scopes:['user.info.basic'],pkce:true}
};
const enc=new TextEncoder();
function base64url(bytes:ArrayBuffer){ return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
async function challenge(verifier:string){ return base64url(await crypto.subtle.digest('SHA-256',enc.encode(verifier))); }
export async function makeAuthorizeUrl(env:WorkerEnv,platform:OAuthPlatform,state:string,verifier:string){ const p=PROVIDERS[platform], client=p.clientId(env); if(!client)throw new Error(`Falta credencial OAuth para ${platform}`); const redirect=`${env.APP_ORIGIN}/api/oauth/${platform}/callback`; const u=new URL(p.auth); u.searchParams.set(platform==='tiktok'?'client_key':'client_id',client); u.searchParams.set('redirect_uri',redirect); u.searchParams.set('response_type','code'); u.searchParams.set('scope',p.scopes.join(platform==='tiktok'?',':' ')); u.searchParams.set('state',state); if(platform==='youtube'){u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');} if(p.pkce){u.searchParams.set('code_challenge',await challenge(verifier));u.searchParams.set('code_challenge_method','S256');} return u.toString(); }
export async function exchangeCode(env:WorkerEnv,platform:OAuthPlatform,code:string,verifier:string){ const p=PROVIDERS[platform], client=p.clientId(env), secret=p.clientSecret(env); if(!client||!secret)throw new Error(`Faltan secretos OAuth para ${platform}`); const redirect=`${env.APP_ORIGIN}/api/oauth/${platform}/callback`; const body=new URLSearchParams({code,grant_type:'authorization_code',redirect_uri:redirect}); body.set(platform==='tiktok'?'client_key':'client_id',client); body.set('client_secret',secret); if(p.pkce)body.set('code_verifier',verifier); const r=await fetch(p.token,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}); const json=await r.json() as any; if(!r.ok)throw new Error(json.error_description||json.message||json.error||`OAuth ${r.status}`); return {accessToken:String(json.access_token||''),refreshToken:json.refresh_token?String(json.refresh_token):null,expiresIn:Number(json.expires_in||0)}; }
export async function profile(env:WorkerEnv,platform:OAuthPlatform,token:string){
 if(platform==='twitch'){ const r=await fetch('https://api.twitch.tv/helix/users',{headers:{Authorization:`Bearer ${token}`,'Client-Id':env.TWITCH_CLIENT_ID||''}}); const j=await r.json() as any; const x=j.data?.[0]; if(!x)throw new Error('Twitch no devolvió usuario'); return {id:String(x.id),name:String(x.display_name||x.login),avatar:x.profile_image_url||null}; }
 if(platform==='youtube'){ const r=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${token}`}}); const x=await r.json() as any; if(!r.ok)throw new Error('Google no devolvió usuario'); return {id:String(x.sub),name:String(x.name||x.email||x.sub),avatar:x.picture||null}; }
 if(platform==='kick'){ const r=await fetch('https://api.kick.com/public/v1/channels',{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}}); const j=await r.json() as any; const x=j.data?.[0]; if(!x)throw new Error('Kick no devolvió canal'); return {id:String(x.broadcaster_user_id),name:String(x.slug||x.broadcaster_user_id),avatar:null}; }
 const r=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,union_id,avatar_url,display_name',{headers:{Authorization:`Bearer ${token}`}}); const j=await r.json() as any; const x=j.data?.user; if(!x)throw new Error('TikTok no devolvió usuario'); return {id:String(x.open_id||x.union_id),name:String(x.display_name||x.open_id),avatar:x.avatar_url||null};
}
export function newOAuthState(){ return {state:randomToken(24),verifier:randomToken(48)}; }

export async function setupTwitchEventSub(env:WorkerEnv,broadcasterId:string){
 const client=env.TWITCH_CLIENT_ID,secret=env.TWITCH_CLIENT_SECRET,webhookSecret=env.TWITCH_WEBHOOK_SECRET;if(!client||!secret||!webhookSecret)return {ok:false,detail:'Faltan secretos Twitch'};
 const tr=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client,client_secret:secret,grant_type:'client_credentials'})});if(!tr.ok)return {ok:false,detail:`App token ${tr.status}`};const tj=await tr.json() as any;const appToken=String(tj.access_token||'');
 const subs=[['channel.follow','2'],['channel.subscribe','1'],['channel.subscription.message','1'],['channel.subscription.gift','1'],['channel.cheer','1'],['channel.raid','1'],['channel.chat.message','1']] as const;let active=0;const failures:string[]=[];
 for(const [type,version] of subs){let condition:Record<string,string>;if(type==='channel.follow')condition={broadcaster_user_id:broadcasterId,moderator_user_id:broadcasterId};else if(type==='channel.raid')condition={to_broadcaster_user_id:broadcasterId};else if(type==='channel.chat.message')condition={broadcaster_user_id:broadcasterId,user_id:broadcasterId};else condition={broadcaster_user_id:broadcasterId};const r=await fetch('https://api.twitch.tv/helix/eventsub/subscriptions',{method:'POST',headers:{'Client-Id':client,Authorization:`Bearer ${appToken}`,'content-type':'application/json'},body:JSON.stringify({type,version,condition,transport:{method:'webhook',callback:`${env.APP_ORIGIN}/webhooks/twitch`,secret:webhookSecret}})});if(r.ok||r.status===202||r.status===409)active++;else failures.push(`${type}:${r.status}`)}return {ok:active>0,active,failures};
}
export async function setupKickSubscriptions(accessToken:string){const events=['chat.message.sent','channel.followed','channel.subscription.new','channel.subscription.renewal','channel.subscription.gifts'].map(name=>({name,version:1}));const r=await fetch('https://api.kick.com/public/v1/events/subscriptions',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'content-type':'application/json',Accept:'application/json'},body:JSON.stringify({method:'webhook',events})});return {ok:r.ok,status:r.status,detail:r.ok?'':(await r.text()).slice(0,180)};}
