import type { WorkerEnv } from './env.js';

const enc=new TextEncoder();
function safe(raw:string){try{return JSON.parse(raw)}catch{return null}}
function within(timestamp:string){const n=Date.parse(timestamp);return Number.isFinite(n)&&Math.abs(Date.now()-n)<10*60_000}
function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function equal(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export async function verifyTwitch(headers:Headers,body:string,secret:string){const id=headers.get('Twitch-Eventsub-Message-Id')||'',ts=headers.get('Twitch-Eventsub-Message-Timestamp')||'',sig=headers.get('Twitch-Eventsub-Message-Signature')||'';if(!id||!ts||!sig||!within(ts))return {ok:false,id,type:''};const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const out=await crypto.subtle.sign('HMAC',key,enc.encode(id+ts+body));return {ok:equal(`sha256=${hex(out)}`,sig),id,type:headers.get('Twitch-Eventsub-Message-Type')||''};}
function pemToBuf(pem:string){const b64=pem.replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,'');const bin=atob(b64);return Uint8Array.from(bin,c=>c.charCodeAt(0)).buffer}
export async function verifyKick(headers:Headers,body:string,publicKey:string){const id=headers.get('Kick-Event-Message-Id')||'',ts=headers.get('Kick-Event-Message-Timestamp')||'',sig=headers.get('Kick-Event-Signature')||'',type=headers.get('Kick-Event-Type')||'';if(!id||!ts||!sig||!within(ts))return {ok:false,id,type};try{const key=await crypto.subtle.importKey('spki',pemToBuf(publicKey),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const bytes=Uint8Array.from(atob(sig),c=>c.charCodeAt(0));return {ok:await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,bytes,enc.encode(`${id}.${ts}.${body}`)),id,type}}catch{return {ok:false,id,type}}}
export async function kickPublicKey(){try{const r=await fetch('https://api.kick.com/public/v1/public-key',{cf:{cacheTtl:3600,cacheEverything:true}} as RequestInit);if(!r.ok)return null;const j=await r.json() as any;return j.data?.public_key||null}catch{return null}}
export function twitchEvent(payload:any,messageId:string){const t=payload?.subscription?.type,e=payload?.event||{};const base={dedupeKey:`twitch:${messageId}`};switch(t){case'channel.chat.message':return{...base,type:'chat_message',actorId:String(e.chatter_user_id||'unknown'),actorName:String(e.chatter_user_name||'Usuario'),message:String(e.message?.text||'')};case'channel.follow':return{...base,type:'follow',actorId:String(e.user_id||'unknown'),actorName:String(e.user_name||'Usuario')};case'channel.subscribe':if(e.is_gift)return null;return{...base,type:'sub',actorId:String(e.user_id||'unknown'),actorName:String(e.user_name||'Usuario'),rawUnit:String(e.tier||'tier')};case'channel.subscription.message':return{...base,type:'resub',actorId:String(e.user_id||'unknown'),actorName:String(e.user_name||'Usuario'),amount:Number(e.cumulative_months||1),rawUnit:String(e.tier||'tier'),message:String(e.message?.text||'')};case'channel.subscription.gift':return{...base,type:'gift_sub',actorId:String(e.user_id||'anonymous'),actorName:String(e.user_name||'Anónimo'),amount:Number(e.total||1),rawUnit:String(e.tier||'gift')};case'channel.cheer':return{...base,type:'bits',actorId:String(e.user_id||'anonymous'),actorName:String(e.user_name||'Anónimo'),amount:Number(e.bits||0),currency:'Bits',rawUnit:'bits',message:String(e.message||'')};case'channel.raid':return{...base,type:'raid',actorId:String(e.from_broadcaster_user_id||'unknown'),actorName:String(e.from_broadcaster_user_name||'Canal'),amount:Number(e.viewers||0),rawUnit:'viewers'};default:return null}}
function userOf(x:any){return{xId:String(x?.user_id||'unknown'),name:String(x?.username||'Usuario')}}
export function kickEvent(type:string,p:any,messageId:string){const base={dedupeKey:`kick:${type}:${messageId}`};if(type==='chat.message.sent'){const u=userOf(p.sender);return{...base,type:'chat_message',actorId:u.xId,actorName:u.name,message:String(p.content||'')}}if(type==='channel.followed'){const u=userOf(p.follower);return{...base,type:'follow',actorId:u.xId,actorName:u.name}}if(type==='channel.subscription.new'){const u=userOf(p.subscriber);return{...base,type:'sub',actorId:u.xId,actorName:u.name,amount:1,rawUnit:'sub'}}if(type==='channel.subscription.renewal'){const u=userOf(p.subscriber);return{...base,type:'resub',actorId:u.xId,actorName:u.name,amount:Number(p.duration||1),rawUnit:'months'}}if(type==='channel.subscription.gifts'){const u=userOf(p.gifter);return{...base,type:'gift_sub',actorId:u.xId,actorName:u.name,amount:Number(p.giftees?.length||0),rawUnit:'gift'}}return null}
export function parseJson(raw:string){return safe(raw)}
export function broadcasterId(platform:'twitch'|'kick',payload:any){if(platform==='twitch')return String(payload?.event?.broadcaster_user_id||payload?.event?.to_broadcaster_user_id||'');return String(payload?.broadcaster?.user_id||'')}
