interface Env { DB:D1Database; ASSETS:Fetcher; APP_ORIGIN:string; UC_PER_UNIT:string }
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const cors=(r:Response)=>{r.headers.set('access-control-allow-origin','*');r.headers.set('access-control-allow-headers','content-type,authorization');r.headers.set('access-control-allow-methods','GET,POST,PUT,DELETE,OPTIONS');return r};
async function hash(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('MonaWorld-v1-static-salt'+s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function token(){return crypto.randomUUID()+'-'+crypto.randomUUID()}
async function auth(req:Request,env:Env){const t=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'';if(!t)return null;const th=await hash(t);const row=await env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(th,Date.now()).first<any>();return row||null}
async function body(req:Request){try{return await req.json()}catch{return {}}}
const defaults=[
 ['follow','Nuevo Follow','all',1,6000,0,'{user} comenzó a seguirte','', '',0],
 ['sub','Nueva Suscripción','all',1,6500,0,'{user} se suscribió','', '',1],
 ['member','Nuevo Miembro','youtube',1,6500,0,'{user} se hizo miembro','', '',1],
 ['bits','Bits / Cheer','twitch',1,6500,1,'{user} envió {amount} Bits','', '',0],
 ['gift','Regalo TikTok','tiktok',1,6500,1,'{user} envió {amount} Coins','', '',0],
 ['donation','Donación','all',1,7000,1,'{user} donó {amount} {unit}','', '',1],
 ['raid','Raid','twitch',1,6500,0,'¡Raid de {user} con {amount}!','', '',1],
 ['share','Compartido','tiktok',1,4500,0,'{user} compartió el LIVE','', '',0],
 ['like','Likes','tiktok',1,3500,1,'{user} envió {amount} likes','', '',0],
 ['chat','Mensaje destacado','all',1,6000,0,'{user}: {message}','','',1]
];
async function ensureTimer(env:Env,userId:number){const r=await env.DB.prepare('SELECT * FROM timers WHERE user_id=?').bind(userId).first<any>();if(!r){await env.DB.prepare('INSERT INTO timers(user_id) VALUES(?)').bind(userId).run();return await env.DB.prepare('SELECT * FROM timers WHERE user_id=?').bind(userId).first<any>();}return r;}
function coinsForEvent(amount:number,unit:string,settings:any){const a=Number(amount||0);const u=String(unit||'').toLowerCase();let base=a;if(u==='bits')base=a/100;else if(u==='coins')base=a*0.01;else if(u==='usd' || u==='eur' || u==='clp')base=a;return Math.max(0,Math.round(base*Number(settings?.monacoins_per_unit||100)));}
async function extendTimer(env:Env,userId:number,monacoins:number){const t=await ensureTimer(env,userId);if(!t||!t.enabled)return;const rate=Number(t.seconds_per_monacoin||0);if(rate<=0)return;const now=Date.now();const current=Math.max(now,Number(t.end_at||0));const maxEnd=now+Number(t.max_seconds||3600)*1000;const end=Math.min(maxEnd,current+monacoins*rate*1000);await env.DB.prepare('UPDATE timers SET end_at=?,updated_at=? WHERE user_id=?').bind(Math.floor(end),now,userId).run();}
async function ensureDefaults(env:Env,userId:number){const c=await env.DB.prepare('SELECT COUNT(*) c FROM alerts WHERE user_id=?').bind(userId).first<any>();if(Number(c?.c||0)===0){const stm=env.DB.prepare('INSERT INTO alerts(user_id,event_type,name,platform,enabled,duration_ms,min_value,template,media_url,sound_url,tts) VALUES(?,?,?,?,?,?,?,?,?,?,?)');await env.DB.batch(defaults.map(d=>stm.bind(userId,...d)));}}
async function api(req:Request,env:Env,url:URL){
 const user=await auth(req,env); const path=url.pathname;
 if(req.method==='POST'&&path==='/api/auth/login'){const b=await body(req);const ph=await hash(String(b.password||''));const u=await env.DB.prepare('SELECT * FROM users WHERE username=? AND password_hash=?').bind(String(b.username||''),ph).first<any>();if(!u)return json({ok:false,error:'Usuario o contraseña incorrectos'},401);const raw=await token();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await hash(raw),u.id,Date.now()+30*864e5).run();return json({ok:true,token:raw,user:{id:u.id,username:u.username,role:u.role}})}
 if(path==='/api/auth/logout'&&req.method==='POST'){if(user){const t=req.headers.get('authorization')!.slice(7);await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(t)).run()}return json({ok:true})}
 if(path==='/api/health')return json({ok:true,service:'MonaWorld',time:new Date().toISOString()});
 if(!user)return json({ok:false,error:'AUTH_REQUIRED'},401);
 await ensureDefaults(env,user.id);
 if(path==='/api/me')return json({user:{id:user.id,username:user.username,role:user.role}});
 if(path==='/api/dashboard'){const [events,platforms,alerts,rewards]=await Promise.all([env.DB.prepare('SELECT * FROM events WHERE user_id=? ORDER BY id DESC LIMIT 30').bind(user.id).all(),env.DB.prepare('SELECT * FROM platforms WHERE user_id=? ORDER BY id').bind(user.id).all(),env.DB.prepare('SELECT * FROM alerts WHERE user_id=? ORDER BY id').bind(user.id).all(),env.DB.prepare('SELECT * FROM rewards WHERE user_id=? ORDER BY id').bind(user.id).all()]);return json({events:events.results,platforms:platforms.results,alerts:alerts.results,rewards:rewards.results});}
 if(path==='/api/timer'&&req.method==='GET'){const publicUser=String(url.searchParams.get('user')||'');const owner=user||(publicUser?await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(publicUser).first<any>():null);if(!owner)return json({timer:null});const t=await ensureTimer(env,owner.id);return json({timer:t});}
 if(path==='/api/timer'&&req.method==='PUT'){const b=await body(req);await ensureTimer(env,user.id);await env.DB.prepare('UPDATE timers SET name=?,initial_seconds=?,max_seconds=?,seconds_per_monacoin=?,enabled=?,auto_start=?,label=?,position_x=?,position_y=?,font_family=?,font_size=?,text_color=?,accent_color=? WHERE user_id=?').bind(String(b.name||'MonaTimer'),Number(b.initial_seconds||600),Math.max(1,Number(b.max_seconds||3600)),Math.max(0,Number(b.seconds_per_monacoin??0.1)),b.enabled?1:0,b.auto_start?1:0,String(b.label||'MonaTimer'),Number(b.position_x??50),Number(b.position_y??15),String(b.font_family||'Inter'),Number(b.font_size||56),String(b.text_color||'#ffffff'),String(b.accent_color||'#ff35d1'),user.id).run();return json({ok:true,timer:await ensureTimer(env,user.id)});}
 if(path==='/api/timer/start'&&req.method==='POST'){const t=await ensureTimer(env,user.id);const now=Date.now();const end=Math.min(now+Number(t.max_seconds||3600)*1000,now+Number(t.initial_seconds||600)*1000);await env.DB.prepare('UPDATE timers SET end_at=?,updated_at=? WHERE user_id=?').bind(end,now,user.id).run();return json({ok:true});}
 if(path==='/api/timer/add'&&req.method==='POST'){const t=await ensureTimer(env,user.id);const b=await body(req);const now=Date.now();const current=Math.max(now,Number(t.end_at||0));const maxEnd=now+Number(t.max_seconds||3600)*1000;const end=Math.min(maxEnd,current+Math.max(0,Number(b.seconds||0))*1000);await env.DB.prepare('UPDATE timers SET end_at=?,updated_at=? WHERE user_id=?').bind(end,now,user.id).run();return json({ok:true,end_at:end});}
 if(path==='/api/timer/reset'&&req.method==='POST'){const t=await ensureTimer(env,user.id);await env.DB.prepare('UPDATE timers SET end_at=?,updated_at=? WHERE user_id=?').bind(0,Date.now(),user.id).run();return json({ok:true});}
 if(path==='/api/settings'&&req.method==='GET'){const s=await env.DB.prepare('SELECT * FROM settings WHERE user_id=?').bind(user.id).first();return json({settings:s});}
 if(path==='/api/settings'&&req.method==='PUT'){const b=await body(req);await env.DB.prepare('INSERT INTO settings(user_id,loyalty_name,monacoins_per_unit,tts_enabled,moderation_mode,theme) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET loyalty_name=excluded.loyalty_name,monacoins_per_unit=excluded.monacoins_per_unit,tts_enabled=excluded.tts_enabled,moderation_mode=excluded.moderation_mode,theme=excluded.theme').bind(user.id,String(b.loyalty_name||'MonaPoints'),Number(b.monacoins_per_unit||100),b.tts_enabled?1:0,String(b.moderation_mode||'balanced'),'neon').run();return json({ok:true});}
 if(path==='/api/alerts'&&req.method==='POST'){const b=await body(req);const id=b.id?Number(b.id):null;if(id){await env.DB.prepare('UPDATE alerts SET name=?,platform=?,enabled=?,duration_ms=?,min_value=?,template=?,media_url=?,sound_url=?,tts=?,voice=?,font_family=?,font_size=?,font_weight=?,text_color=?,accent_color=?,position_x=?,position_y=?,animation=? WHERE id=? AND user_id=?').bind(b.name,b.platform,b.enabled?1:0,Number(b.duration_ms||6000),Number(b.min_value||0),b.template||'',b.media_url||'',b.sound_url||'',b.tts?1:0,b.voice||'es-ES',b.font_family||'Inter',Number(b.font_size||48),Number(b.font_weight||700),b.text_color||'#fff',b.accent_color||'#ff3bd4',Number(b.position_x??50),Number(b.position_y??50),b.animation||'pop',id,user.id).run();return json({ok:true,id})}const r=await env.DB.prepare('INSERT INTO alerts(user_id,event_type,name,platform,template) VALUES(?,?,?,?,?)').bind(user.id,b.event_type||'custom',b.name||'Nueva alerta',b.platform||'all',b.template||'{user} activó la alerta').run();return json({ok:true,id:r.meta.last_row_id});}
 if(path.startsWith('/api/alerts/')&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM alerts WHERE id=? AND user_id=?').bind(Number(path.split('/').pop()),user.id).run();return json({ok:true});}
 if(path==='/api/rewards'&&req.method==='POST'){const b=await body(req);const r=await env.DB.prepare('INSERT INTO rewards(user_id,name,cost,type,payload_json) VALUES(?,?,?,?,?)').bind(user.id,b.name||'Recompensa',Number(b.cost||100),b.type||'sound',JSON.stringify(b.payload||{})).run();return json({ok:true,id:r.meta.last_row_id});}
 if(path==='/api/platforms/connect'&&req.method==='POST'){const b=await body(req);await env.DB.prepare('INSERT INTO platforms(user_id,platform,enabled,connected,display_name,config_json) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,platform) DO UPDATE SET enabled=excluded.enabled,connected=excluded.connected,display_name=excluded.display_name,config_json=excluded.config_json').bind(user.id,b.platform,1,b.demo?1:0,b.display_name||'',JSON.stringify(b.config||{})).run();return json({ok:true,mode:b.demo?'demo':'oauth_pending'});}
 if(path==='/api/events/test'&&req.method==='POST'){const b=await body(req);const amount=Number(b.amount||0),unit=b.unit||'',settings=await env.DB.prepare('SELECT * FROM settings WHERE user_id=?').bind(user.id).first<any>();const mc=coinsForEvent(amount,unit,settings);const r=await env.DB.prepare('INSERT INTO events(user_id,platform,event_type,user_name,amount,unit,message,payload_json) VALUES(?,?,?,?,?,?,?,?)').bind(user.id,b.platform||'twitch',b.event_type||'follow',b.user_name||'Viewer',amount,unit,b.message||'',JSON.stringify({...b,monacoins:mc})).run();if(['bits','gift','donation','superchat','member_gift','sticker'].includes(String(b.event_type||'').toLowerCase())&&mc>0)await extendTimer(env,user.id,mc);return json({ok:true,id:r.meta.last_row_id,monacoins:mc});}
 if(path==='/api/events'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT * FROM events WHERE user_id=? ORDER BY id DESC LIMIT 50').bind(user.id).all();return json({events:rows.results});}
 if(path==='/api/overlay/events'&&req.method==='GET'){const since=Number(url.searchParams.get('since')||0);const publicUser=String(url.searchParams.get('user')||'');const overlayUser=user || (publicUser ? await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(publicUser).first<any>() : null);if(!overlayUser)return json({events:[]});const rows=await env.DB.prepare('SELECT * FROM events WHERE user_id=? AND id>? AND processed=0 ORDER BY id ASC LIMIT 20').bind(overlayUser.id,since).all();if(rows.results.length)await env.DB.prepare(`UPDATE events SET processed=1 WHERE user_id=? AND id<=?`).bind(overlayUser.id,rows.results[rows.results.length-1].id).run();return json({events:rows.results});}
 if(path==='/api/sounds'&&req.method==='POST'){const b=await body(req);if(!String(b.data||'').startsWith('data:audio/'))return json({error:'Solo audio data URLs'},400);if(String(b.data).length>2_000_000)return json({error:'Archivo demasiado grande. Máximo 1.5 MB aprox.'},413);const r=await env.DB.prepare('INSERT INTO sounds(user_id,name,mime,data) VALUES(?,?,?,?)').bind(user.id,b.name||'sound',b.mime||'audio/mpeg',b.data).run();return json({ok:true,id:r.meta.last_row_id});}
 if(path==='/api/sounds'&&req.method==='GET'){const r=await env.DB.prepare('SELECT id,name,mime,created_at FROM sounds WHERE user_id=? ORDER BY id DESC').bind(user.id).all();return json({sounds:r.results});}
 return json({error:'NOT_FOUND'},404);
}
export default {async fetch(req:Request,env:Env){if(req.method==='OPTIONS')return cors(new Response(null,{status:204}));const url=new URL(req.url);let r:Response;if(url.pathname.startsWith('/api/'))r=await api(req,env,url);else r=await env.ASSETS.fetch(req);return cors(r)}};
